lane :test do
  update_project_codesigning(path: "demo-project/demo/demo.xcodeproj")
end
lane :test_toggle do
  update_project_codesigning(path: "demo-project/demo/demo.xcodeproj")
  update_project_codesigning(path: "demo-project/demo/demo.xcodeproj", use_automatic_signing: true)
end

lane :oldproject do
  update_project_codesigning(path: "demo-old-app/HelloCordova.xcodeproj", use_automatic_signing: true)
end